platform:
  - x86
  - x64
configuration:
  - Debug
  - Release

branches:
  only: master
skip_tags: true
os:
  - Visual Studio 2015

build:
  parallel: true
  verbosity: normal

install:
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat
  -

build_script:
  - cmake --build build --target check
