#!/bin/sh
# travis-install - build-script

if [[ "Darwin" = $(uname -s) && ${CXX} == "g++" ]]; then
  brew tap homebrew/versions
  brew install gcc${VERSION/./}
fi

if [[ "Darwin" = $(uname -s) ]]; then
  brew ls | grep -wq cmake || brew install --without-docs cmake
  brew outdated cmake || brew upgrade cmake
fi
