#!/bin/sh
# travis-configure - build-script

CURRENT=$(pwd)
if [[ ! -z ${VERSION} ]]; then
  CXX=${CXX}-${VERSION}
  CC=${CC}-${VERSION}
fi

echo Using $(cmake --version | head -n1)
echo CXX=${CXX}

mkdir build && cd build || exit 1

cmake $CURRENT \
  -DCMAKE_CXX_COMPILER:STRING=${CXX} \
  -DCMAKE_BUILD_TYPE:STRING=${BUILD:-Debug} \
  -DBUILD_WITH_COVERAGE:BOOL=ON \
  -DBUILD_WITH_LIBCXX:BOOL=${LIBCXX:-OFF} \
  -DBUILD_TESTING:BOOL=ON
