#!/bin/sh
# travis-configure - build-script

if [[ "Darwin" = $(uname -s) && ${CXX} == "g++" ]]; then
  brew tap homebrew/versions
  brew install gcc${VERSION/./}
fi

if [[ "Darwin" = $(uname -s) ]]; then
  if [[ ! -z $(brew ls --versions cmake) ]]; then
    brew install --without-docs cmake
  fi
  brew outdated cmake || brew upgrade cmake
fi
