#!/bin/sh
# travis-before-install - build-script

# This is apparently an expected approach in the event brew update fails on
# the first try. Wat.
if [[ "Darwin" = $(uname -s) ]]; then
  brew update || brew update || exit 1
  brew upgrade
fi
