#!/bin/sh
# Written in 2015 by MNMLSTC
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty. You should have
# received a copy of the CC0 Public Domain Dedication along with this software.
# If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.

VERSION=3.3.2
URL=https://cmake.org/files/v3.3/cmake-$VERSION-$(uname -s)-x86_64.tar.gz

function version { $HOME/cmake/bin/cmake --version | head -n1; }

if [[ -d $HOME/cmake && $VERSION = $(version | sed s/[^0-9]*//) ]]; then
  echo Using $(version) && exit 0
fi

curl $URL -o cmake.tar.gz || exit 1
tar xzf cmake.tar.gz -C cmake --strip-components=1
ls $HOME/cmake
